### ISSUE TITLE
what is the module path?

### ISSUE THREAD

**Issue by satanu01** [opensignature/pdfsign#1]
Hello,
I am using PKCS11 USB token for PDF sign and I am in Ubuntu. I can not find the module path, can pls help that with where I will get that module?

**Comment by opensignature** [comment]
module is a library provided by the token provider like:
libbit4opki.so (Oberthur)
opensc-pkcs11.so (OpenSC)
libASEP11.so (Athena)
libeTPkcs11.so (SafeNet)
libsiecap11.so (Siemens)
